name = "skland-daily-attendance"
compatibility_date = "2025-12-26"
compatibility_flags = ["nodejs_als"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "6428ec29a2564f62a2ca1515075711a2"

[triggers]
crons = ["30 0/2 * * *"]
